/// Model representing a medicine record in the CarePharma inventory.
class Medicine {
  const Medicine({
    this.uid,
    required this.name,
    required this.priceInr,
    required this.type,
    required this.stock,
    required this.manufacturer,
    required this.expiryDate,
    this.pharmacyUid,
    this.addedBy,
    this.genericSalt,
  });

  /// Unique identifier generated by backend/database.
  final String? uid;

  /// Trade or generic name of medicine.
  final String name;

  /// Price in Indian Rupees (₹).
  final double priceInr;

  /// Formulation type (e.g., Tablet, Capsule, Syrup, Ointment, Drops, Inhaler).
  final String type;

  /// In-stock quantity (strips/bottles/units).
  final int stock;

  /// Manufacturing pharmaceutical company.
  final String manufacturer;

  /// Expiry date (e.g., "2027-02-03" or "11/2026").
  final String expiryDate;

  /// Unique identifier of the pharmacy that owns this inventory record.
  final String? pharmacyUid;

  /// Audit field recording the user who created/modified this item.
  final String? addedBy;

  /// Active chemical molecule / generic salt composition (e.g., "Paracetamol IP 650mg").
  final String? genericSalt;

  /// Whether the item is completely out of stock.
  bool get isOutOfStock => stock <= 0;

  /// Whether the item is running low on stock (< 15 units).
  bool get isLowStock => stock > 0 && stock < 15;

  /// Human-readable stock health description.
  String get stockHealth {
    if (isOutOfStock) return 'Out of Stock';
    if (isLowStock) return 'Low Stock';
    return 'Good';
  }

  /// Formatted price with Rupee symbol.
  String get formattedPrice => '₹${priceInr.toStringAsFixed(2)}';

  /// Deserializes a Medicine from Supabase JSON map, handling both
  /// capitalized and snake_case column names seamlessly.
  factory Medicine.fromJson(Map<String, dynamic> json) {
    // Handle price conversion safely from int/double/string
    double parsePrice(dynamic val) {
      if (val == null) return 0.0;
      if (val is num) return val.toDouble();
      return double.tryParse(val.toString()) ?? 0.0;
    }

    // Handle stock conversion safely
    int parseStock(dynamic val) {
      if (val == null) return 0;
      if (val is num) return val.toInt();
      return int.tryParse(val.toString()) ?? 0;
    }

    final rawUid = json['UID'] ?? json['uid'] ?? json['id'];
    final rawName = json['Name'] ?? json['name'] ?? '';
    final rawPrice = parsePrice(json['Price_INR'] ?? json['price_inr'] ?? json['price']);
    final rawType = json['Type'] ?? json['type'] ?? 'Tablet';
    final rawStock = parseStock(json['Stock'] ?? json['stock']);
    final rawManufacturer = json['Manufacturer'] ?? json['manufacturer'] ?? '';
    final rawExpiry = json['Expiry_Date'] ?? json['expiry_date'] ?? json['expiry'] ?? '';
    final rawPharmacyUid = json['pharmacy_uid'] ?? json['Pharmacy_UID'] ?? json['pharmacy_id'];
    final rawAddedBy = json['added_by'] ?? json['Added_By'];
    final rawGenericSalt = json['generic_salt'] ?? json['Generic_Salt'] ?? json['salt_composition'];

    return Medicine(
      uid: rawUid?.toString(),
      name: rawName.toString(),
      priceInr: rawPrice,
      type: rawType.toString(),
      stock: rawStock,
      manufacturer: rawManufacturer.toString(),
      expiryDate: rawExpiry.toString(),
      pharmacyUid: rawPharmacyUid?.toString(),
      addedBy: rawAddedBy?.toString(),
      genericSalt: rawGenericSalt?.toString(),
    );
  }

  /// Serializes the Medicine for Supabase queries.
  /// Generates the payload adhering to the Supabase schema.
  Map<String, dynamic> toJson({bool includeUid = false}) {
    final map = <String, dynamic>{
      'Name': name,
      'Price_INR': priceInr,
      'Type': type,
      'Stock': stock,
      'Manufacturer': manufacturer,
      'Expiry_Date': expiryDate,
    };

    if (includeUid && uid != null && uid!.isNotEmpty) {
      map['UID'] = uid;
    }

    if (pharmacyUid != null && pharmacyUid!.isNotEmpty) {
      map['pharmacy_uid'] = pharmacyUid;
    }

    if (addedBy != null && addedBy!.isNotEmpty) {
      map['added_by'] = addedBy;
    }

    if (genericSalt != null && genericSalt!.isNotEmpty) {
      map['generic_salt'] = genericSalt;
    }

    return map;
  }

  /// Returns a copy of this medicine with modified attributes.
  Medicine copyWith({
    String? uid,
    String? name,
    double? priceInr,
    String? type,
    int? stock,
    String? manufacturer,
    String? expiryDate,
    String? pharmacyUid,
    String? addedBy,
    String? genericSalt,
  }) {
    return Medicine(
      uid: uid ?? this.uid,
      name: name ?? this.name,
      priceInr: priceInr ?? this.priceInr,
      type: type ?? this.type,
      stock: stock ?? this.stock,
      manufacturer: manufacturer ?? this.manufacturer,
      expiryDate: expiryDate ?? this.expiryDate,
      pharmacyUid: pharmacyUid ?? this.pharmacyUid,
      addedBy: addedBy ?? this.addedBy,
      genericSalt: genericSalt ?? this.genericSalt,
    );
  }
}

